### ISSUE TITLE
Recent update broke playback

### ISSUE THREAD

**Issue by wfowler1** [ScroogeD2/owmidiconverter#11]
At some point recently, an update to the game broke playback. Sometimes notes are missed or played entirely out of sync. This is pretty obvious when listening to the Moonlight 3rd Movement track.

**Comment by ScroogeD2** [comment]
I can't seem to reproduce any problems with playback. Could you add me as a friend on Discord (ScroogeD#5147) to discuss this more?

**Comment by ScroogeD2** [comment]
Issue resolved, the example workshop codes in the README were outdated. New codes are included in b752966f746433b138564b8d2cd102bf38f4fe86.
