### ISSUE TITLE
Cannot be used after the March 9th update

### ISSUE THREAD

**Issue by expelFune** [ScroogeD2/owmidiconverter#12]
Error: There should be an option after "Current array element," on line 102

**Comment by ScroogeD2** [comment]
Hi, I wasn't able to reproduce that exact problem, but I did just push a fix for two other bugs that had popped up due to the workshop script being outdated. Could you add me on Discord (ScroogeD#5147) so we could figure out which thing is bugging out for you?

**Comment by expelFune** [comment]
I know what's going on，简体中文（Simplified Chinese） can not be used. Errors occur when using 简体中文( simplified Chinese).
(Sorry,my network cannot connect to discord)

**Comment by ScroogeD2** [comment]
The issues should be fixed with 76820069f8918c76697194cc213dadd676a5431f. Blizzard had updated some workshop translations, which broke the translations a little.

Thanks for the report!
