### ISSUE TITLE
midi file is oversize, how can I play it?

### ISSUE THREAD

**Issue by sqksyftx** [ScroogeD2/owmidiconverter#13]
Thanks for your contribution, that's cool！
I try to transform a 2009 seconds midi file but it just has 52% (1049 seconds）, how should I play it perfectly?

**Comment by ScroogeD2** [comment]
This is unfortunately a size problem, as the workshop has a script size limit and your file contains more data than the workshop can save. The midi data could be compressed further, but I likely won't have time for it in the near future.
