### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ajk2113** [ScroogeD2/owmidiconverter#17]
First of all, I cannot thank you enough for this game mode. The amount of joy these lobbies bring me is insane. <3 Anyway, when trying to copy from clip board, i'm getting Error: Global variable '42' has invalid name and it does not copy the mode over. I tested it on a few different songs. hope there is a fix and thanks again :)

**Comment by ScroogeD2** [comment]
Thanks for the report, fixed with 8edfc57fb8eefcb546d082ec14409daa800d4946. Blizzard's word filter changed at some point, and apparently "K" and "k" are invalid variable names now and were causing the issue.
