### ISSUE TITLE
Add "goto" function

### ISSUE THREAD

**Issue by sengjung123** [ScroogeD2/owmidiconverter#7]
Since there's a loop function now, it would be really helpful, if it's possible, if there is a "goto" function to jump to a certain point of the song.

**Comment by ScroogeD2** [comment]
I'm actually planning to ditch loops altogether. There aren't really many uses for them and they take up workshop script size, which could be greatly reduced by getting rid of them (and gotos).

**Comment by sengjung123** [comment]
to be fair, loops and gotos are actually great at compressing full-length songs in a musical sense, since most songs actually replay certain parts of their tune before jumping into their ending. 

To put it in a musical way, its similar to D.S. al coda, where D.S. is a loop once, and coda is to jump to a certain point in the music(normally after D.S.) to the end.

**Comment by ScroogeD2** [comment]
Indeed, but there is currently no way to add them except manually editing the script. And frankly, I don't have the UI expertise required to make something usable for adding them easily.

**Comment by ScroogeD2** [comment]
Loops have been removed with 898fb89432847b6e812ea921d62b63cea52579e3. I currently have no plans for adding them back, even though they were convenient in certain circumstances.
